baseurl = "https://mcwertgaming.github.io/"
languageCode = "en-us"
copyright = "This blog is published under the terms of the MIT License. Don't distribute or publish this blogs posts without permission!"
rssLimit = 20
theme = "terminal"
paginate = 5
enableRobotsTXT = true

[author]
  name = "Damon Leven"
  email = "mcwertgaming@gmail.com"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  posts = "/:year/:title/"

[params]
  AuthorName = "Damon Leven"
  GitHubUser = "mcwertgaming"

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = true
  # default language
  defaultContentLanguage = "en"

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  favicon = "img/favicon/favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "staxthefox"
  # site = ""

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/english"
    title = "OpenFoxBlog"
    subtitle = "A Blog about programming and technology along with furry and lifestyle."
    owner = "Damon Leven"
    keywords = ["programming", "technology", "C++", "Cpp", "fox", "opensource", "tutorials"]
    copyright = "© 2020 Damon Leven"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "OpenFoxBlog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/contact/#rss-feeds"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 3

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/deutsch"
    title = "OpenFoxBlog"
    subtitle = "Ein Blog über Programmierung und Technologie, aber auch Furry und Lifestyle."
    owner = "Damon Leven"
    keywords = ["Programmierung", "Technologie", "C++", "Cpp", "Furry", "fox", "opensource", "Tutorials"]
    copyright = "© 2020 Damon Leven"
    menuMore = "Mehr anzeigen"
    readMore = "Weiter lesen"
    readOtherPosts = "Andere Posts lesen"
    missingContentMessage = "Seite existiert nicht..."
    missingBackButtonLabel = "Zurück zur Startseite"

    [languages.de.params.logo]
      logoText = "OpenFoxBlog"
      logoHomeLink = "/de"

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/de/kontakt/#rss-feeds"
        weight = 1
      [[languages.de.menu.main]]
        identifier = "über mich"
        name = "Über mich"
        url = "/de/über-mich"
        weight = 2
      [[languages.de.menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/de/kontakt"
        weight = 3
